name: Release Please

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      # create release commit
      contents: write
      # create release PR
      pull-requests: write
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 🆕 Create or update release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  npm-publish:
    needs: [release-please]
    runs-on: ubuntu-latest
    # Only run if a release was created
    if: ${{ needs.release-please.outputs.releases_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - run: pnpm publish -r --access public --no-git-checks
        env:
          NPM_EMAIL: jacob.ebey@live.com
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
