name: Release Please

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      # create release commit
      contents: write
      # create release PR
      pull-requests: write
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 🆕 Create or update release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  npm-publish:
    permissions: write-all
    needs: [release-please]
    runs-on: ubuntu-latest
    # Only run if a release was created
    if: ${{ needs.release-please.outputs.releases_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          strategy: upgrade
          package: ./packages/resolver
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          strategy: upgrade
          package: ./packages/typegen
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          strategy: upgrade
          package: ./packages/config
